/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import controllers.GastosDAO;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.Gastos;

/**
 *
 * @author muril
 */
public class telaLancamento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaLancamento.class.getName());

    /**
     * Creates new form telaLancamento
     */
    public telaLancamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_descrição = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        lbl_valor = new javax.swing.JLabel();
        lbl_categoria = new javax.swing.JLabel();
        txt_descricao = new javax.swing.JTextField();
        txt_valor = new javax.swing.JTextField();
        cbx_categoria = new javax.swing.JComboBox<>();
        botao_sair = new javax.swing.JButton();
        botao_lancar = new javax.swing.JButton();
        botao_voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_userID = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_descrição.setText("Descrição");

        lbl_data.setText("Data");

        lbl_valor.setText("Valor");

        lbl_categoria.setText("Categoria");

        cbx_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Carro", "Casa", "Internet/Telefone", "Saúde", "Mercado", "Lazer", "Misc" }));
        cbx_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_categoriaActionPerformed(evt);
            }
        });

        botao_sair.setText("Sair");
        botao_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_sairActionPerformed(evt);
            }
        });

        botao_lancar.setText("Lançar");
        botao_lancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_lancarActionPerformed(evt);
            }
        });

        botao_voltar.setText("Voltar");
        botao_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_voltarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\muril\\OneDrive\\Documentos\\NetBeansProjects\\piPoo\\src\\main\\java\\imagens\\iconeAvatar.png")); // NOI18N

        lbl_userID.setText("Admin");

        txt_data.setName("txt_data"); // NOI18N
        txt_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botao_voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_sair)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(botao_lancar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_descrição, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_categoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbx_categoria, 0, 129, Short.MAX_VALUE)
                    .addComponent(txt_valor)
                    .addComponent(txt_descricao)
                    .addComponent(txt_data))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(lbl_userID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_descrição)
                                    .addComponent(txt_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(lbl_data)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_valor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_categoria)
                            .addComponent(cbx_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botao_lancar))
                    .addComponent(jLabel1)
                    .addComponent(lbl_userID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_sair)
                    .addComponent(botao_voltar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_sairActionPerformed
         new telaLogin1().setVisible(true);
                this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_botao_sairActionPerformed

    private void botao_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_voltarActionPerformed
        new telaMenu1().setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_botao_voltarActionPerformed

    private void botao_lancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_lancarActionPerformed
        try {
            String descricao = txt_descricao.getText().trim();
            String textoValor = txt_valor.getText().trim();
            String textoData = txt_data.getText().trim();
            String categoria = cbx_categoria.getSelectedItem().toString();

            if (descricao.isEmpty() || textoValor.isEmpty() || textoData.isEmpty() || categoria.equals("Selecione")) {
                JOptionPane.showMessageDialog(
                        this,
                        "Todos os campos são obrigatórios!",
                        "Erro ao registrar",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            double valor;
            try {
                valor = Double.parseDouble(textoValor.replace(",", "."));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Valor inválido! Digite um número válido.\nExemplo: 100.50",
                        "Erro no valor",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            LocalDate data;
            try {
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                data = LocalDate.parse(textoData, formatter);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                        this,
                        "Data inválida! Utilize o formato dd/MM/yyyy.\nExemplo: 25/11/2025",
                        "Erro na data",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
            
            Gastos g = new Gastos(descricao, valor, data, categoria);
            new GastosDAO().inserir(g);

            JOptionPane.showMessageDialog(this, "Lançamento salvo com sucesso!");

            txt_descricao.setText("");
            txt_valor.setText("");
            txt_data.setText("");
            cbx_categoria.setSelectedIndex(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro inesperado.\n" + e.getMessage());
        }

    }//GEN-LAST:event_botao_lancarActionPerformed

    private void txt_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dataActionPerformed

    private void cbx_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_categoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new telaLancamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_lancar;
    private javax.swing.JButton botao_sair;
    private javax.swing.JButton botao_voltar;
    private javax.swing.JComboBox<String> cbx_categoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_categoria;
    private javax.swing.JLabel lbl_data;
    private javax.swing.JLabel lbl_descrição;
    private javax.swing.JLabel lbl_userID;
    private javax.swing.JLabel lbl_valor;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txt_descricao;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
